### PR TITLE
Add buttons for fdroid and google play store

### PR DESCRIPTION
**Pull request by Poussinou**
two beautiful buttons with links to fdroid and google play store

### CODE REVIEW

**Comment by erickok** [comment]
If you add a similar button for my own site, that's be great. :)

**Comment by Poussinou** [comment]
Hum I do not know much about HTML5...

Maybe merge this PR, and feel free to reuse the code of the buttons on your website 👍

**Comment by danielquinn** [comment]
I know enough to do this, but @erickok, while the other buttons say "get it on `platform-name`", what would you prefer your button to say?

**Comment by erickok** [comment]
"get it on transdroid.org"

**Comment by danielquinn** [comment]
Here you go.  Sorry for the delay!

get-it-on-transdroid

**Comment by danielquinn** [comment]
Here you go.  Sorry for the delay!

get-it-on-transdroid

**Pull request merged**
