### PR TITLE
rtorrent: axmlrpc updated

### PR DESCRIPTION
**Pull request by fbarriga**
This PR made changes on axmlrpc that is being use by rtorrent adapter.

The changes are from [WordPress Android Client](https://github.com/wordpress-mobile/WordPress-Android).

Changes:
- Use XmlPullParser to parse the incoming xml file

What does fix:
- Crash when seeding more than 4.000 torrents (usually run out of memory while parsing)
- Performance Improvement. Parsing the xml with the list of torrents now takes ~3 seconds instead of 90 seconds!

I've tested it with rtorrent and works good so far.

### CODE REVIEW

**Comment by fbarriga** [comment]
ON HOLD, need further testing.

**Comment by erickok** [comment]
Thanks for your contribution. It is very interesting. As it happens I have slowly started work again on Transdroid and part of that is to renew/upgrade all the clients. I started with rTorrent. The new work will be based around a more modern architecture and libraries, which should also be much faster.

As part of this effort I have written https://github.com/erickok/retrofit-xmlrpc which will be used to connect to rTorrent's XML-RPC. I have not tested with 9000+ torrents yet, that would be very interesting to do.

**Comment by fbarriga** [comment]
@erickok that's great. When you have any progress on the new rtorrent client let me now to test it.
Do you have any new features in mind ?

**Comment by erickok** [comment]
It will be quite a work to just get feature parity (with so many supported clients), so... yes but for the far future?

**Comment by Niluge-KiWi** [comment]
Would it be possible to merge this before the complete rewrite ? This is already written.
I have performance issues with somewhat large number of torrents (n*100), this would help !

**Comment by fbarriga** [comment]
@erickok Maybe we could have a **beta** or **rtorrent enhanced beta** on Google Play while the refactor is being done. I can rebase this PR if you want and then upload this branch as a new app on Google Play.

**Comment by erickok** [comment]
I'll merge and make a (beta maybe) release on Thursday.

**Pull request merged**
