### PR TITLE
Add qbittorrent features

### PR DESCRIPTION
**Pull request by H3mul**
Following up on an old issue of mine (#191 ). Finally got around to it!

Fully implemented sequential download and first-last piece priority for qBittorrent. Tested on a real device. Let me know if anything is amiss.

screenshot_transdrone

### CODE REVIEW

**Comment by erickok** [comment]
This is really nice, thank you! Is this working with qbittorrent 4.2?

**Comment by H3mul** [comment]
I'm on 4.1.9 currently, I'll test with 4.2 this weekend

**Comment by H3mul** [comment]
So, it looks like in 4.2, qbittorrent dropped all "legacy" api commands. For instance, the `/login` endpoint doesn't exist anymore, it's now `/api/v2/auth/login`. Similarly, the command structure of other calls has changed. The qbittorrent WebUI used this newer API for a while now, but seemed also supported the "legacy" API Transdrone used all this time, until 4.2.

I'm interested in Transdroid and qBittorrent, so I'll be glad to integrate the new v2 API.

Source:
https://github.com/qbittorrent/qBittorrent/blob/master/Changelog#L76

**Comment by erickok** [comment]
Yes indeed. A contribution to support the new endpoints would be amazing, thanks!

**Pull request merged**
